# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: cd /mnt/c/Users/daniel/Desktop/git/mimostiapi
    - run: cp ./* ./mimostiapi_dev/    
    - run: npm ci
    - run: npm run build --if-present
    - run: npm i -g javascript-obfuscator pkg
    - run: Copy-Item package.json dist/
    - run: Copy-Item src/main.js dist/
    - run: npm test
    - run: cd dist
    - run: pkg . --targets node18-win-x64 --output mimostiapi.exe
    - run: rcedit.exe mimostiapi.exe --set-icon ..\\logo.ico
